import Style, { StyleFunction } from 'ol/style/Style';
import { IdGenerator } from '../../../common/id.generator';

/**
 * A layer that is responsible for showing and styling main features on the map, such as markers and polygons
 */
export class FeatureLayerSettings {
  /**
   * The identifier of the field, it is autogenerated by default, but can be set manually
   */
  name: string = IdGenerator.get();
  /**
   * The priority of showing - layers with higher zIndex cover others in case of collisions
   */
  zIndex: number = 1;
  /**
   * The maximum zoom at which the layer is visible. 19 by default
   */
  maxZoom: number = 19;
  /**
   * The minimum zoom at which the layer is visible. 0 by default
   */
  minZoom: number = 0;
  /**
   * The styling definition of layer's features. The easiest way is to use {@link PolygonStyleHelper},{@link MarkerStyleHelper}
   */
  style?: Style | StyleFunction;

  /**
   * Creates a clone of the existing settings
   * @param model
   */
  public static copy(model: FeatureLayerSettings): FeatureLayerSettings {
    const result = new FeatureLayerSettings();
    result.name = model.name;
    result.maxZoom = model.maxZoom;
    result.minZoom = model.minZoom;
    result.zIndex = model.zIndex;
    result.style = model.style;
    return result;
  }

  /**
   Setter for {@link FeatureLayerSettings.zIndex}
   * @param zIndex
   */
  setZIndex(zIndex: number): FeatureLayerSettings {
    return FeatureLayerSettings.copy({ ...this, zIndex });
  }

  /**
   * Setter for {@link FeatureLayerSettings.name}
   * @param name
   */
  setName(name: string): FeatureLayerSettings {
    return FeatureLayerSettings.copy({ ...this, name });
  }

  /**
   * Setter for {@link FeatureLayerSettings.maxZoom}
   * @param maxZoom
   */
  setMaxZoom(maxZoom: number): FeatureLayerSettings {
    return FeatureLayerSettings.copy({ ...this, maxZoom });
  }

  /**
   * Setter for {@link FeatureLayerSettings.minZoom}
   * @param minZoom
   */
  setMinZoom(minZoom: number): FeatureLayerSettings {
    return FeatureLayerSettings.copy({ ...this, minZoom });
  }

  /**
   * Setter for {@link FeatureLayerSettings.style}
   * @param style
   */
  setStyle(style: Style | StyleFunction): FeatureLayerSettings {
    return FeatureLayerSettings.copy({ ...this, style });
  }

  /**
   * Checks if the model has the same content
   * @param model - the object to compare
   */
  public isSame(model: FeatureLayerSettings): boolean {
    if (this.maxZoom !== model.maxZoom) return false;
    if (this.minZoom !== model.minZoom) return false;
    if (this.zIndex !== model.zIndex) return false;
    if (this.name !== model.name) return false;
    if (this.style !== model.style) return false;
    return true;
  }
}
